version: 0.2

env:
  variables:
    CODE_SRC_DIR: "."
    NONESENSE_EVAR: "ACHRAF BAIZ"

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      # Install httpie
      - curl -SsL https://packages.httpie.io/deb/KEY.gpg | apt-key add -
      - curl -SsL -o /etc/apt/sources.list.d/httpie.list https://packages.httpie.io/deb/httpie.list
      - apt update
      - apt install httpie
  build:
    commands:
      - ls -l
      - http PUT pie.dev/put X-API-Token:123 name=John

artifacts:
  files:
    - '**/*'